services:

  app:
    build: .
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - default

  nginx:
    image: nginx:1.25.3
    ports:
      - ${WEB_PORT:-8000}:80
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - default

  mysql:
    image: mysql:8.2.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - ${MYSQL_PORT:-3306}:3306
    volumes:
      - data:/var/lib/mysql
    networks:
      - default

  adminer:
    image: adminer:4.17.1
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
    ports:
      - ${ADMINER_PORT:-8080}:8080
    depends_on:
      - mysql
    networks:
      - default

volumes:
  data:

networks:
  default:
